{"pyct.error_utils": [], "pyct.error_utils._stack_trace_inside_mapped_code": ["<builtin>.tuple", "pyct.origin_info.LineLocation", "<builtin>.reversed"], "<builtin>.reversed": [], "pyct.origin_info.LineLocation": [], "<builtin>.tuple": [], "pyct.error_utils.MultilineMessageKeyError.__init__": ["<builtin>.super"], "<builtin>.super": [], "pyct.error_utils.MultilineMessageKeyError.__str__": [], "pyct.error_utils.ErrorMetadataBase.__init__": ["pyct.error_utils._stack_trace_inside_mapped_code"], "pyct.error_utils.ErrorMetadataBase.get_message": ["<builtin>.len", "util.traceback_utils.is_traceback_filtering_enabled", "util.traceback_utils.include_frame", "<builtin>.range", "<builtin>.reversed"], "util.traceback_utils.is_traceback_filtering_enabled": [], "util.traceback_utils.include_frame": [], "<builtin>.len": [], "<builtin>.range": [], "pyct.error_utils.ErrorMetadataBase.create_exception": ["pyct.error_utils.ErrorMetadataBase.get_message", "<builtin>.type", "pyct.error_utils.MultilineMessageKeyError.__init__"], "<builtin>.type": [], "pyct.error_utils.ErrorMetadataBase.to_exception": ["pyct.error_utils.ErrorMetadataBase.create_exception"]}