{"Desktop\\Work\\tensorflow-master\\tensorflow\\python\\eager\\core": ["tensorflow.python.pywrap_tfe.TFE_Py_RegisterExceptionClass", "tensorflow.python.pywrap_tfe.TFE_Py_RegisterFallbackExceptionClass"], "Desktop\\Work\\tensorflow-master\\tensorflow\\python\\eager\\core._status_to_exception": ["tensorflow.python.framework.errors.UnknownError", "tensorflow.python.framework.errors.exception_type_from_error_code"], "tensorflow.python.framework.errors.exception_type_from_error_code": [], "tensorflow.python.framework.errors.UnknownError": [], "Desktop\\Work\\tensorflow-master\\tensorflow\\python\\eager\\core._NotOkStatusException.__init__": ["<builtin>.super"], "<builtin>.super": [], "Desktop\\Work\\tensorflow-master\\tensorflow\\python\\eager\\core._NotOkStatusException.__str__": ["Desktop\\Work\\tensorflow-master\\tensorflow\\python\\eager\\core._status_to_exception"], "tensorflow.python.pywrap_tfe.TFE_Py_RegisterExceptionClass": [], "tensorflow.python.pywrap_tfe.TFE_Py_RegisterFallbackExceptionClass": []}
